#!/bin/bash
if [[ -z "$1" ]]; then echo "usage: $0 <input-file>"; exit 1; fi
TMPF=/tmp/mk_errtab.$$
nv=$(expr $(wc -l < "$1") + 2)
echo -e "#ifndef __qwe_cfgtab_inc\n#define __qwe_cfgtab_inc\n"
echo -e "// generated by \"$0\" from \"$1\" on $(date)\n"
echo -e "struct cfg_ent { int i, i_d, i_m, i_M; const char *s, *s_vd; };"

grep -on '^[a-zA-Z0-9_]*' "$1" | sed 's/\(^[0-9]*\):\(.*$\)/#define CFG_\2 (cfg_tab[\1])/'

echo -e "\n#ifndef QWE_DEFINE_CFGTAB\nextern cfg_ent cfg_tab[$nv];\n#else"
echo -e "cfg_ent cfg_tab[$nv] = {{0,0,0,0,0}, "

sed 's/ *|/|/g' "$1" | awk '-F|' \
	'{ if ($2=="s") print "{ 0,0,0x7fffffff," 65536*$4+$5 ",0,\"LF_"$1"\\0"$3"\" },";
		else print "{"$3","$3","$4","$5",0,\"LF_"$1"\\0\"\""$3"\"},"; } '

echo -e "{0,0,0,0,0}}; \n#endif // define_cfgtab\n\n#endif  // __qwe_cfgtab_inc"




