#!/bin/bash
if [[ -z "$1" ]]; then echo "usage: $0 <input-file>"; exit 1; fi
TMPF=/tmp/mk_errtab.$$
echo -e "#ifndef __qwe_errtab_inc\n#define __qwe_errtab_inc\n"
echo -e "// generated by \"$0\" from \"$1\" on $(date)\n"

grep -on '^[a-zA-Z0-9_]* *' "$1" | sed 's/\(^[0-9]*\):\(.*$\)/#define \2 (-\1)/'

echo -e "\n#ifndef QWE_DEFINE_ERRTAB\nconst char * err_str(int ec);\n#else"
echo -e "const char * err_str(int ec) {\n    static const char * tab[] = {\"no error\","
sed 's/^[a-zA-Z0-9_]* */        "/;s/$/",/' "$1"
echo "        \"this error message is supposed to be _really_ invisible\" };"
echo "    if (ec>0) return \"invalid error code (>0)\";"
echo "    if (ec<ERRTAB_LAST) return \"invalid error code (<0)\";"
echo "    if (ec==EEE_ERRNO) return strerror(errno);"
echo "    return tab[-ec]; }"

		
echo -e "#endif // errtab\n\n#endif  // __qwe_errtab_inc"




