#!/bin/bash
tmpf=/tmp/imm-$$
(echo "#include <stdio.h>"
 echo "#include <stdlib.h>"
 echo "#include <math.h>"
 echo "#include <limits.h>"
 echo "int main() { int i,j,k; double x,y,z; char *p,*q,*r; "
 echo "return printf(\"%$1\\n\", ($2)), 0; }" ) > $tmpf.c
#echo "---"; cat $tmpf.c; echo "---"
(cc -o $tmpf.b $tmpf.c -lm && $tmpf.b) || cat $tmpf.c
rm $tmpf.c $tmpf.b
