:sy match comment /^{{{.*/
:sy match comment /^S[0-9][_0-9][_0-9]___.*(BUG)__/
:sy match identifier /^\/\/?.*/
:sy match identifier /^[A-Z][A-Z]E_[_A-Za-z0-9]*/
:sy match keyword /^==>/
:sy match string /`\.[^`]*`/
:sy match string /^<.*$/
:sy match string /^^<.*$/
:sy match PreProc /^#\(.*\\\n\)*.*/
