#!/bin/bash
if [[ "$1" != "-" ]]; then
	asv=$HOME/.lflab/__asv.lf
	cp $HOME/g/lflab/t/qtst-asv$1.lf $asv
	$HOME/lf-prod/s/lf $asv & 
	/bin/sleep .5
fi
find /run/shm -type p -name A
$HOME/lf.cmd.playback >>/run/shm/lf.*/A <$HOME/g/lflab/t/tc/t$2
